module.exports = () => ({
  jobImageRegistry: "jobImageRegistry",
  jobImagePath: "jobImagePath",
  prodImageRegistry: "prodImageRegistry",
  prodImagePath: "prodImagePath",
  registeryUsername: "registeryUsername",
  registeryPassword: "registeryPassword",
  defaultFromEmail: "defaultFromEmail",
  defaultSystemPassword: "defaultSystemPassword",
  decidimTimezone: "decidimTimezone",
  webhookUrl: "webhookUrl",
  webhookUsername: "webhookUsername",
  webhookHMAC: "webhookHMAC",
  smtpHost: "smtpHost",
  smtpPort: "smtpPort",
  smtpUsername: "smtpUsername",
  smtpPassword: "smtpPassword",
  smtpAuthentication: "smtpAuthentication",
  smtpOpenTimeout: "smtpOpenTimeout",
  smtpReadTimeout: "smtpReadTimeout",
  nodeGroup: "nodeGroup",
  webhookPassword: "webhookPassword",
  instanceUUID: "instanceUUID",
});
