include:
  - project: o/infra/templates
    file: /gitlab-ci/includes/jobs.yaml

tests:backend:
  stage: test
  coverage: /All\sfiles.*?\s+(\d+.\d+)/
  image: node:16.14.0-alpine3.14
  only:
    - merge_requests
    - main
  cache:
    key: node_modules
    paths:
      - backend/node_modules
  script:
    - cd backend
    - yarn
    - yarn test:cov
    - yarn test:ci
  artifacts:
    when: always
    reports:
      junit:
        - backend/junit.xml


tests:frontend:
  stage: test
  coverage: /All\sfiles.*?\s+(\d+.\d+)/
  image: node:16.13.0-alpine3.14
  only:
    - merge_requests
    - main
  cache:
    key: front_node_modules
    paths:
      - frontend/node_modules
  script:
    - cd frontend
    - yarn
    - yarn lint
    - yarn test:ci
    - yarn test:cov
  artifacts:
    when: always
    reports:
      junit:
        - frontend/junit.xml


build:backend:
  stage: build
  needs: ["tests:backend"]
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: "$CI_COMMIT_TAG =~ /v.*$/"
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - "[[ -f VERSION.txt ]] && VERSION=$(cat VERSION.txt) || VERSION=${CI_COMMIT_TAG:-$CI_COMMIT_SHORT_SHA}"
    - /kaniko/executor --context $CI_PROJECT_DIR/backend --dockerfile $CI_PROJECT_DIR/backend/Dockerfile --destination $CI_REGISTRY_IMAGE/backend:$VERSION --build-arg VERSION=$VERSION
    - VERSION=${CI_COMMIT_TAG:-latest}
    - echo "{\"auths\":{\"https://index.docker.io/v1/\":{\"auth\":\"$DOCKERHUB_AUTH\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR/backend --dockerfile $CI_PROJECT_DIR/backend/Dockerfile --destination octree/voca-system-backend:$VERSION --build-arg VERSION=$VERSION

build:frontend:
  stage: build
  needs: ["tests:frontend"]
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: "$CI_COMMIT_TAG =~ /v.*$/"
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - "[[ -f VERSION.txt ]] && VERSION=$(cat VERSION.txt) || VERSION=${CI_COMMIT_TAG:-$CI_COMMIT_SHORT_SHA}"
    - /kaniko/executor --context $CI_PROJECT_DIR/frontend --dockerfile $CI_PROJECT_DIR/frontend/Dockerfile --destination $CI_REGISTRY_IMAGE/frontend:$VERSION --build-arg VERSION=$VERSION
    - VERSION=${CI_COMMIT_TAG:-latest}
    - echo "{\"auths\":{\"https://index.docker.io/v1/\":{\"auth\":\"$DOCKERHUB_AUTH\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR/frontend --dockerfile $CI_PROJECT_DIR/frontend/Dockerfile --destination octree/voca-system-frontend:$VERSION --build-arg VERSION=$VERSION

deploy:backend:
  extends: .deployJelastic
  needs: ["build:backend"]
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: "$CI_COMMIT_TAG =~ /v.*$/"
  environment:
    name: Prod Backend
    url: "https://api.voca.city"

deploy:frontend:
  extends: .deployJelastic
  needs: ["build:frontend", "deploy:backend"]
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: "$CI_COMMIT_TAG =~ /v.*$/"
  environment:
    name: Prod Frontend
    url: "https://app.voca.city"


version:
  extends: .release
