include:
  - project: o/infra/templates
    file: /gitlab-ci/includes/StrapiBuildDeploy.yaml
  - project: o/infra/templates
    file: /gitlab-ci/includes/jobs.yaml

tests:api:
  stage: test
  coverage: /All\sfiles.*?\s+(\d+.\d+)/
  image: node:16.14.0-alpine3.14
  only:
    - merge_requests
    - main
  cache:
    key: node_modules
    paths:
      - api/node_modules
  script:
    - echo "45.66.221.1 npm-8ee.hidora.com" >> /etc/hosts
    - cd backend
    - yarn
    - yarn test:cov
    - yarn test:ci
tests:app:
  stage: test
  coverage: /All\sfiles.*?\s+(\d+.\d+)/
  image: node:16.14.0-alpine3.14
  only:
    - merge_requests
    - main
  cache:
    key: front_node_modules
    paths:
      - app/node_modules
  script:
    - echo "45.66.221.1 npm-8ee.hidora.com" >> /etc/hosts
    - cd frontend
    - yarn
    - yarn test:ci  
    - test:cov

build:latest:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  only:
    - merge_requests
    - main
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - "[[ -f VERSION.txt ]] && VERSION=$(cat VERSION.txt) || VERSION=${CI_COMMIT_TAG:-$CI_COMMIT_SHORT_SHA}"
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:latest --build-arg VERSION=$VERSION

build:nginx:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  only:
    - merge_requests
    - main
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR/nginx --dockerfile $CI_PROJECT_DIR/Dockerfile-nginx --destination $CI_REGISTRY_IMAGE/nginx:latest --build-arg JELASTIC_HOST=${JELASTIC_HOST:-jcloud-ver-jpc.ik-server.com}
