include:
  - template: SAST.gitlab-ci.yml
    rules:
      - if: '$CI_COMMIT_REF_NAME == "master"'
      - if: '$CI_COMMIT_REF_NAME == "main"'
  - project: o/infra/templates
    file: /gitlab-ci/includes/jobs.yaml

tests:backend:
  stage: test
  coverage: /All\sfiles.*?\s+(\d+.\d+)/
  image: node:16.14.0-alpine3.14
  only:
    - merge_requests
    - main
  cache:
    key: node_modules
    paths:
      - backend/node_modules
  script:
    - echo "45.66.221.1 npm-8ee.hidora.com" >> /etc/hosts
    - cd backend
    - yarn
    - yarn test:cov
    - yarn test:ci

tests:frontend:
  stage: test
  coverage: /All\sfiles.*?\s+(\d+.\d+)/
  image: node:16.13.0-alpine3.14
  only:
    - merge_requests
    - main
  cache:
    key: front_node_modules
    paths:
      - frontend/node_modules
  script:
    - echo "45.66.221.1 npm-8ee.hidora.com" >> /etc/hosts
    - cd frontend
    - yarn
    - yarn lint
    - yarn test:ci  
    - yarn test:cov

build:front-back:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  only:
    - merge_requests
    - main
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - "[[ -f VERSION.txt ]] && VERSION=$(cat VERSION.txt) || VERSION=${CI_COMMIT_TAG:-$CI_COMMIT_SHORT_SHA}"
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile-backend --destination $CI_REGISTRY_IMAGE/backend:latest --build-arg VERSION=$VERSION
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile-frontend --destination $CI_REGISTRY_IMAGE/frontend:latest --build-arg VERSION=$VERSION

build:nginx:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  only:
    - merge_requests
    - main
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR/nginx --dockerfile $CI_PROJECT_DIR/Dockerfile-nginx --destination $CI_REGISTRY_IMAGE/nginx:latest --build-arg JELASTIC_HOST=${JELASTIC_HOST:-jcloud-ver-jpc.ik-server.com}

release:front-back:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  only:
    - tags
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - "[[ -f VERSION.txt ]] && VERSION=$(cat VERSION.txt) || VERSION=${CI_COMMIT_TAG:-$CI_COMMIT_SHORT_SHA}"
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile-backend --destination $CI_REGISTRY_IMAGE/backend:$VERSION --build-arg VERSION=$VERSION
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile-frontend --destination $CI_REGISTRY_IMAGE/frontend:$VERSION --build-arg VERSION=$VERSION

release:nginx:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  only:
    - tags
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR/nginx --dockerfile $CI_PROJECT_DIR/Dockerfile-nginx --destination $CI_REGISTRY_IMAGE/nginx:$VERSION --build-arg JELASTIC_HOST=${JELASTIC_HOST:-jcloud-ver-jpc.ik-server.com}

version:
  extends: .release
