FROM nginx:1.20-alpine
ARG JELASTIC_HOST=jcloud-ver-jpc.ik-server.com
ENV JELASTIC_HOST=$JELASTIC_HOST

RUN apk add --upgrade --no-cache certbot certbot-nginx

# Volume to stores the public directories of strapi and next
VOLUME /data/frontend
VOLUME /data/backend
VOLUME /etc/letsencrypt

COPY ./data /data
COPY ./conf.d /etc/nginx/conf.d/
