fragment UserFields on UsersPermissionsMe {
  id
  username
  email
  confirmed
}

mutation Register($username: String!, $email: String!, $password: String!) {
  register(input: {username: $username, email: $email, password: $password}) {
    user {
      ...UserFields
    }
  }
}

mutation Login($identifier: String!, $password: String!) {
  login(input: {identifier: $identifier, password: $password}) {
    jwt
    user {
      ...UserFields
    }
  }
}

mutation Forgot($email: String!) {
  forgotPassword(email: $email) {
    ok
  }
}

mutation Reset(
  $password: String!
  $passwordConfirmation: String!
  $code: String!
) {
  resetPassword(
    password: $password
    passwordConfirmation: $passwordConfirmation
    code: $code
  ) {
    user {
      confirmed
    }
    jwt
  }
}
