mutation firstInstall($user: UserInput!, $instance: InstanceInstallInput!) {
  firstInstall(user: $user, instance: $instance) {
    ok
  }
}
query Instances {
  instances {
    data {
      id
      attributes {
        title
        envName
        status
      }
    }
  }
}
