#!/bin/bash
set -e
TAG="${CI_COMMIT_TAG:-latest}"
REG=$CI_REGISTRY_IMAGE
DOCKER_PATH="$CI_PROJECT_DIR/.docker/Dockerfile"
while IFS=";" read -r decidim_version major_version minor_version node_version ruby_version
do
    if [ $minor_version = $DECIDIM_VERSION ]; then
        REP_GRP="$major_version.$minor_version"
        /kaniko/executor \
            --context "$CI_PROJECT_DIR/.docker" \
            --dockerfile $DOCKER_PATH-saas \
            --build-arg DECIDIM_VERSION=$decidim_version \
            --build-arg ALPINE_PATH=$REG/$REP_GRP:toolkit-alpine-$TAG \
            --build-arg QUICKSTART_PATH=$REG/$REP_GRP:quickstart-$TAG \
            --destination $REG/vocacity:$major_version.$minor_version \
            --cache 
        break
    fi
done < versions.csv