---
name: Decidim
description:
  text: Decidim install by Octree
ssl: true
type: install
logo: https://d33wubrfki0l68.cloudfront.net/151a960cdc5eff60d6c41b70814d2f017384c78e/f4599/images/decidim-logo-topbar.svg

globals:
  DB_PASSWORD: ${fn.password(24)}
  APP_SESSION_KEY: ${fn.password(6)}
  SECRET_KEY_BASE: ${fn.password(128)}
  MASTER_KEY: ${fn.password(32)}
settings:
  fields:
    - type: string
      name: IMAGE_REGISTRY
      caption: Registry URL
      default: git.octree.ch:4567
      tooltip: "Docker Registry URL"
    - type: string
      name: IMAGE_PATH
      caption: Image path
      default: decidim/decidim-quickstart/vocacity:0.24
      tooltip: "Image path inside the registry"
    - type: compositefield
      caption: Username/Password for Registry
      name: IMAGE_AUTH
      defaultMargins:
        top: 0
        right: 0
        bottom: 0
        left: 10
      items:
        - width: 150
          name: IMAGE_USERNAME
          type: string
          tooltip: "Username used to authenticate with the registry"
        - width: 150
          name: IMAGE_PASSWORD
          type: string
          inputType: password
          tooltip: "Password used to authenticate with the registry"

    - type: compositefield
      caption: Decidim Email/Password of System User
      name: DECIDIM_SYSTEM
      defaultMargins:
        top: 0
        right: 0
        bottom: 0
        left: 10
      items:
        - width: 150
          name: DECIDIM_DEFAULT_SYSTEM_EMAIL
          type: string
          inputType: email
          tooltip: "This email will be used to create the instance"
        - width: 150
          name: DECIDIM_DEFAULT_SYSTEM_PASSWORD
          type: string
          inputType: password
          tooltip: "This password will be used to create the instance"
    - type: compositefield
      caption: Decidim Long/Short name of instance
      name: DECIDIM_NAMING
      defaultMargins:
        top: 0
        right: 0
        bottom: 0
        left: 10
      items:
        - width: 150
          name: DECIDIM_NAME
          type: string
          inputType: string
          tooltip: "This name will appear in the system dashboard"
        - width: 75
          name: DECIDIM_SHORTNAME
          type: string
          tooltip: "An acronym that will prefix all your official documents."
    - type: list
      caption: Decidim Timezone
      name: TIMEZONE
      values:
        GMT+12/GMT+12: GMT+12/GMT+12
        Pacific/Midway: Pacific/Midway
        Pacific/Pago_Pago: Pacific/Pago_Pago
        Pacific/Honolulu: Pacific/Honolulu
        America/Juneau: America/Juneau
        America/Los_Angeles: America/Los_Angeles
        America/Tijuana: America/Tijuana
        America/Denver: America/Denver
        America/Phoenix: America/Phoenix
        America/Chihuahua: America/Chihuahua
        America/Mazatlan: America/Mazatlan
        America/Chicago: America/Chicago
        America/Regina: America/Regina
        America/Mexico_City: America/Mexico_City
        America/Monterrey: America/Monterrey
        America/Guatemala: America/Guatemala
        America/New_York: America/New_York
        America/Bogota: America/Bogota
        America/Lima: America/Lima
        America/Halifax: America/Halifax
        America/Caracas: America/Caracas
        America/La_Paz: America/La_Paz
        America/Santiago: America/Santiago
        America/St_Johns: America/St_Johns
        America/Sao_Paulo: America/Sao_Paulo
        Argentina/Buenos_Aires: Argentina/Buenos_Aires
        America/Montevideo: America/Montevideo
        America/Guyana: America/Guyana
        America/Puerto_Rico: America/Puerto_Rico
        America/Godthab: America/Godthab
        Atlantic/South_Georgia: Atlantic/South_Georgia
        Atlantic/Azores: Atlantic/Azores
        Atlantic/Cape_Verde: Atlantic/Cape_Verde
        Europe/Dublin: Europe/Dublin
        Europe/London: Europe/London
        Europe/Lisbon: Europe/Lisbon
        Africa/Casablanca: Africa/Casablanca
        Africa/Monrovia: Africa/Monrovia
        Etc/UTC: Etc/UTC
        Europe/Belgrade: Europe/Belgrade
        Europe/Bratislava: Europe/Bratislava
        Europe/Budapest: Europe/Budapest
        Europe/Ljubljana: Europe/Ljubljana
        Europe/Prague: Europe/Prague
        Europe/Sarajevo: Europe/Sarajevo
        Europe/Skopje: Europe/Skopje
        Europe/Warsaw: Europe/Warsaw
        Europe/Zagreb: Europe/Zagreb
        Europe/Brussels: Europe/Brussels
        Europe/Copenhagen: Europe/Copenhagen
        Europe/Madrid: Europe/Madrid
        Europe/Paris: Europe/Paris
        Europe/Amsterdam: Europe/Amsterdam
        Europe/Berlin: Europe/Berlin
        Europe/Zurich: Europe/Zurich
        Europe/Rome: Europe/Rome
        Europe/Stockholm: Europe/Stockholm
        Europe/Vienna: Europe/Vienna
        Africa/Algiers: Africa/Algiers
        Europe/Bucharest: Europe/Bucharest
        Africa/Cairo: Africa/Cairo
        Europe/Helsinki: Europe/Helsinki
        Europe/Kiev: Europe/Kiev
        Europe/Riga: Europe/Riga
        Europe/Sofia: Europe/Sofia
        Europe/Tallinn: Europe/Tallinn
        Europe/Vilnius: Europe/Vilnius
        Europe/Athens: Europe/Athens
        Europe/Istanbul: Europe/Istanbul
        Europe/Minsk: Europe/Minsk
        Asia/Jerusalem: Asia/Jerusalem
        Africa/Harare: Africa/Harare
        Africa/Johannesburg: Africa/Johannesburg
        Europe/Kaliningrad: Europe/Kaliningrad
        Europe/Moscow: Europe/Moscow
        Europe/Volgograd: Europe/Volgograd
        Europe/Samara: Europe/Samara
        Asia/Kuwait: Asia/Kuwait
        Asia/Riyadh: Asia/Riyadh
        Africa/Nairobi: Africa/Nairobi
        Asia/Baghdad: Asia/Baghdad
        Asia/Tehran: Asia/Tehran
        Asia/Muscat: Asia/Muscat
        Asia/Baku: Asia/Baku
        Asia/Tbilisi: Asia/Tbilisi
        Asia/Yerevan: Asia/Yerevan
        Asia/Kabul: Asia/Kabul
        Asia/Yekaterinburg: Asia/Yekaterinburg
        Asia/Karachi: Asia/Karachi
        Asia/Tashkent: Asia/Tashkent
        Asia/Kolkata: Asia/Kolkata
        Asia/Kathmandu: Asia/Kathmandu
        Asia/Dhaka: Asia/Dhaka
        Asia/Colombo: Asia/Colombo
        Asia/Almaty: Asia/Almaty
        Asia/Novosibirsk: Asia/Novosibirsk
        Asia/Rangoon: Asia/Rangoon
        Asia/Bangkok: Asia/Bangkok
        Asia/Jakarta: Asia/Jakarta
        Asia/Krasnoyarsk: Asia/Krasnoyarsk
        Asia/Shanghai: Asia/Shanghai
        Asia/Chongqing: Asia/Chongqing
        Asia/Hong_Kong: Asia/Hong_Kong
        Asia/Urumqi: Asia/Urumqi
        Asia/Kuala_Lumpur: Asia/Kuala_Lumpur
        Asia/Singapore: Asia/Singapore
        Asia/Taipei: Asia/Taipei
        Australia/Perth: Australia/Perth
        Asia/Irkutsk: Asia/Irkutsk
        Asia/Ulaanbaatar: Asia/Ulaanbaatar
        Asia/Seoul: Asia/Seoul
        Asia/Tokyo: Asia/Tokyo
        Asia/Yakutsk: Asia/Yakutsk
        Australia/Darwin: Australia/Darwin
        Australia/Adelaide: Australia/Adelaide
        Australia/Melbourne: Australia/Melbourne
        Australia/Sydney: Australia/Sydney
        Australia/Brisbane: Australia/Brisbane
        Australia/Hobart: Australia/Hobart
        Asia/Vladivostok: Asia/Vladivostok
        Pacific/Guam: Pacific/Guam
        Pacific/Port_Moresby: Pacific/Port_Moresby
        Asia/Magadan: Asia/Magadan
        Asia/Srednekolymsk: Asia/Srednekolymsk
        Pacific/Guadalcanal: Pacific/Guadalcanal
        Pacific/Noumea: Pacific/Noumea
        Pacific/Fiji: Pacific/Fiji
        Asia/Kamchatka: Asia/Kamchatka
        Pacific/Majuro: Pacific/Majuro
        Pacific/Auckland: Pacific/Auckland
        Pacific/Tongatapu: Pacific/Tongatapu
        Pacific/Fakaofo: Pacific/Fakaofo
        Pacific/Chatham: Pacific/Chatham
        Pacific/Apia: Pacific/Apia 
      hideLabel: false
      hidden: false
      editable: false
    - type: string
      name: WEBHOOK_URL
      caption: Webhooks URL that handle POST request
      default: app.voca.city/api/webhooks
      tooltip: "This url will be used to send all the events of your instance."
    - type: compositefield
      caption: Webhooks Username/Password for Basic Auth
      name: WEBHOOK_AUTH
      defaultMargins:
        top: 0
        right: 0
        bottom: 0
        left: 10
      items:
        - width: 150
          name: WEBHOOK_USERNAME
          type: string
          inputType: string
          tooltip: "Username to use for a Basic Authentication"
        - width: 150
          name: WEBHOOK_PASSWORD
          type: string
          inputType: password
          default: ${fn.password(12)}
          tooltip: "Password to use for a Basic Authentication"
    - type: string
      name: WEBHOOK_HMAC
      caption: Webhook HMAC key signature
      default: ${fn.password(24)}
      tooltip: "The secret HMAC key that will be used to sign webhook."
    - type: compositefield
      caption: SMTP Address
      name: SMTP_CONNECT
      defaultMargins:
        top: 0
        right: 0
        bottom: 0
        left: 10
      items:
        - width: 150
          name: SMTP_HOST
          type: string
          inputType: string
          placeholder: smtp.sendgrid.com
          tooltip: "Remote SMTP server."
        - width: 10
          type: displayfield
          caption: ":"
          name: smtp_separator
        - width: 75
          name: SMTP_PORT
          inputType: string 
          type: string
          placeholder: 587

    - type: compositefield
      caption: SMTP Username/Password 
      name: SMTP_AUTH
      defaultMargins:
        top: 0
        right: 0
        bottom: 0
        left: 10
      items:
        - width: 150
          name: SMTP_USERNAME
          type: string
          placeholder: api_key
          tooltip: "If your mail server requires authentication, set the username in this setting."
        - width: 150
          name: SMTP_PASSWORD
          type: string
          inputType: password
          placeholder: sg.${fn.password(24)}
          tooltip: "If your mail server requires authentication, set the password in this setting"
        - width: 100
          type: list
          name: SMTP_AUTHENTICATION
          caption: Authentication method 
          values:
            plain: plain
            login: login
            cram_md5: cram_md5
          tooltip:  your mail server requires authentication, you need to specify the authentication type here

    - type: string
      name: SMTP_HELO_DOMAIN
      caption: SMTP Helo Domain
      tooltip: If you need to specify a HELO domain, you can do it here.
    - type: number
      name: SMTP_OPEN_TIMEOUT
      caption: SMTP open timeout in sec.
      default: 5
    - type: number
      name: SMTP_READ_TIMEOUT
      caption: SMTP read timeout in sec.
      default: 5



nodes:
  # NGINX
  - cloudlets: 2
    diskLimit: 5G
    nodeGroup: bl
    nodeType: nginx-dockerized
    tag: 1.20.2
    volumes:
      - /public
    volumeMounts:
      /public:
        protocol: NFS4
        readOnly: true
        sourceNodeGroup: storage
        sourcePath: /data

  # Decidim
  - cloudlets: 8
    diskLimit: 100G
    env:
      APP_SESSION_KEY: ${globals.APP_SESSION_KEY}
      DATABASE_HOST: psql
      DATABASE_PASSWORD: ${globals.DB_PASSWORD}
      DATABASE_USERNAME: postgres
      DATABASE_URL: postgres://postgres:${globals.DB_PASSWORD}@psql:5432/decidim
      SECRET_KEY_BASE: ${globals.SECRET_KEY_BASE}
      MASTER_KEY: ${globals.MASTER_KEY}
      SMTP_ADDRESS: smtp.mailtrap.io
      SMTP_AUTHENTICATION: cram_md5
      SMTP_DOMAIN: smtp.mailtrap.io
      SMTP_USERNAME:
      SMTP_PASSWORD:
      SMTP_PORT: 2525
      SMTP_STARTTLS_AUTO: true
      TZ: ${settings.TIMEZONE}
      RAILS_ROOT: /home/decidim/app
    links:
      - sqldb:psql
    image: ${settings.IMAGE_PATH}
    registry:
      url: ${settings.IMAGE_REGISTRY}
      user: ${settings.IMAGE_USERNAME}
      password: ${settings.IMAGE_PASSWORD}
    nodeGroup: cp
    volumes:
      - /home/decidim/app/public
    volumeMounts:
      /home/decidim/app/public:
        protocol: NFS4
        readOnly: false
        sourceNodeGroup: storage
        sourcePath: /data

  # Decidim
  - cloudlets: 4
    diskLimit: 5G
    env:
      APP_SESSION_KEY: ${globals.APP_SESSION_KEY}
      DATABASE_HOST: psql
      DATABASE_PASSWORD: ${globals.DB_PASSWORD}
      DATABASE_USERNAME: postgres
      DATABASE_URL: postgres://postgres:${globals.DB_PASSWORD}@psql:5432/decidim
      SECRET_KEY_BASE: ${globals.SECRET_KEY_BASE}
      SMTP_ADDRESS: smtp.mailtrap.io
      SMTP_AUTHENTICATION: cram_md5
      SMTP_DOMAIN: smtp.mailtrap.io
      SMTP_USERNAME:
      SMTP_PASSWORD:
      SMTP_PORT: 2525
      SMTP_STARTTLS_AUTO: true
      TZ: ${settings.TIMEZONE}
      DOCKER_EXPOSED_PORT: 3000
      PORT: 3000
    links:
      - sqldb:psql
    image: ${settings.IMAGE_PATH}
    registry:
      url: ${settings.IMAGE_REGISTRY}
      user: ${settings.IMAGE_USERNAME}
      password: ${settings.IMAGE_PASSWORD}
    nodeGroup: cp
    volumes:
      - /home/decidim/app/public
    volumeMounts:
      /home/decidim/app/public:
        protocol: NFS4
        readOnly: false
        sourceNodeGroup: storage
        sourcePath: /data


  # Postgres
  - cloudlets: 3
    diskLimit: 100G
    nodeGroup: sqldb
    nodeType: postgresql
    tag: 14.1
    isSLBAccessEnabled: false
    env:
      POSTGRES_PASSWORD: ${globals.DB_PASSWORD}
      POSTGRES_DB: decidim
      TZ: ${settings.TIMEZONE}
      PGTZ: ${settings.TIMEZONE}
      ADMINPANEL_ENABLED: false
    volumes:
      - "/var/lib/postgresql/data"
    # TODO CREATE USER FOR DECIDIM (restricted permission)
  # Node storage
  - cloudlets: 1
    diskLimit: 100G
    nodeGroup: storage
    nodeType: storage
    tag: 2.0-9.4
    isSLBAccessEnabled: false
    env:
      HOME_DIR: /data
    volumes:
      - "/data"


success: |
  ## Your Decidim is ready !
  See it on [${env.url}](${env.url})
